-- Protocol: Run this SQL in your Supabase SQL Editor

-- 1. Machine Readings (Timeseries Data)
CREATE TABLE IF NOT EXISTS machine_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    temperature FLOAT,
    vibration FLOAT,
    power FLOAT,
    status TEXT
);

-- 2. Fault Rules (Expert System Knowledge Base)
CREATE TABLE IF NOT EXISTS fault_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symptom_keywords TEXT[], -- e.g. ['vibration', 'noise']
    diagnosis TEXT NOT NULL,
    action TEXT NOT NULL,
    confidence FLOAT,
    severity TEXT -- 'Low', 'Medium', 'Critical'
);

-- 3. Maintenance Logs (Technician Workflow)
CREATE TABLE IF NOT EXISTS maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    diagnosis_id BIGINT REFERENCES fault_rules(id),
    technician_action TEXT, -- 'Acknowledged', 'Part Ordered', 'Fixed'
    notes TEXT,
    resolved BOOLEAN DEFAULT FALSE
);

-- Seed Data for Fault Rules (20+ Examples)
INSERT INTO fault_rules (symptom_keywords, diagnosis, action, confidence, severity) VALUES
(ARRAY['vibration', 'noise', 'grinding'], 'Bearing Seizure', 'Replace Bearing Assembly', 0.95, 'Critical'),
(ARRAY['temperature', 'heat', 'smoke'], 'Motor Overheating', 'Check Cooling Fan & Vents', 0.90, 'Critical'),
(ARRAY['power', 'fluctuation'], 'Voltage Instability', 'Inspect Power Supply Unit', 0.85, 'Medium'),
(ARRAY['vibration', 'misalignment'], 'Shaft Misalignment', 'Realign Motor Shaft', 0.88, 'Medium'),
(ARRAY['noise', 'clunking'], 'Gearbox Wear', 'Inspect Gear Teeth', 0.80, 'Medium'),
(ARRAY['temperature', 'coolant'], 'Coolant Pump Failure', 'Replace Pump', 0.92, 'Critical'),
(ARRAY['pressure', 'leak'], 'Hydraulic Leak', 'Seal/Replace Hose', 0.89, 'High'),
(ARRAY['sensor', 'data'], 'Sensor Drift', 'Recalibrate Sensor', 0.75, 'Low'),
(ARRAY['network', 'timeout'], 'PLC Comm Failure', 'Check Ethernet Cable', 0.85, 'Medium'),
(ARRAY['vibration', 'fan'], 'Fan Blade Damage', 'Replace Fan', 0.82, 'Low'),
(ARRAY['oil', 'level'], 'Low Lubrication', 'Top up Oil', 0.95, 'Medium'),
(ARRAY['belt', 'slip'], 'Drive Belt Loose', 'Tension/Replace Belt', 0.87, 'Low'),
(ARRAY['fuse', 'blown'], 'Electrical Short', 'Replace Fuse/Check Circuit', 0.98, 'Critical'),
(ARRAY['software', 'error'], 'HMI Freeze', 'Reboot Control Panel', 0.90, 'Low'),
(ARRAY['valve', 'stuck'], 'Pneumatic Valve Stuck', 'Lubricate/Replace Valve', 0.86, 'Medium'),
(ARRAY['filter', 'clogged'], 'Air Filter Blockage', 'Replace Air Filter', 0.94, 'Low'),
(ARRAY['coupling', 'loose'], 'Coupling Wear', 'Tighten/Replace Coupling', 0.83, 'Medium'),
(ARRAY['bearing', 'heat'], 'Bearing Lubrication Failure', 'Grease Bearing', 0.91, 'High'),
(ARRAY['motor', 'hum'], 'Phase Imbalance', 'Check Electrical Phases', 0.88, 'High'),
(ARRAY['safety', 'stop'], 'E-Stop Triggered', 'Reset Safety Circuit', 1.00, 'Critical');
